





// ------------------------------------------------------------------------------
//  <auto-generated>
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated. 
//  </auto-generated>
// ------------------------------------------------------------------------------

#region Designer generated code
#pragma warning disable

namespace SelAutomationRedesign.Pages
{
	using WebAutomation.Core.WebObjects.Common.Attributes;
	using WebAutomation.Core.WebObjects.WebComponents;
	using WebAutomation.Core.WebObjects.WebComponents.Attributes;
	using WebAutomation.Core.WebObjects.WebContainer;
	using WebAutomation.Core.WebObjects.WebContainer.Attributes;

	[Name("Github")]
	public partial class Github 
	{
		[Name("GlobalHeaderMenu")]
		[Xpath("//div/div[2]/nav/ul")]
		public IWebComponent GlobalHeaderMenu { get; set; }

		[Name("GlobalHeaderMenu_Features")]
		[Xpath("//div/div[2]/nav/ul/li[1]")]
		public IWebComponent GlobalHeaderMenu_Features { get; set; }

		[Name("GlobalHeaderMenu_Business")]
		[Xpath("//div/div[2]/nav/ul/li[2]")]
		public IWebComponent GlobalHeaderMenu_Business { get; set; }

		[Name("GlobalHeaderMenu_Explore")]
		[Xpath("//div/div[2]/nav/ul/li[3]")]
		public IWebComponent GlobalHeaderMenu_Explore { get; set; }

		[Name("GlobalHeaderMenu_Marketplace")]
		[Xpath("//div/div[2]/nav/ul/li[4]")]
		public IWebComponent GlobalHeaderMenu_Marketplace { get; set; }

		[Name("GlobalHeaderMenu_Pricing")]
		[Xpath("//div/div[2]/nav/ul/li[5]")]
		public IWebComponent GlobalHeaderMenu_Pricing { get; set; }

	}

}

#pragma warning restore
#endregion

