





// ------------------------------------------------------------------------------
//  <auto-generated>
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated. 
//  </auto-generated>
// ------------------------------------------------------------------------------

#region Designer generated code
#pragma warning disable

namespace SelAutomationRedesign.Pages
{
	using WebAutomation.Core.WebObjects.Common.Attributes;
	using WebAutomation.Core.WebObjects.WebComponents;
	using WebAutomation.Core.WebObjects.WebComponents.Attributes;
	using WebAutomation.Core.WebObjects.WebContainer;
	using WebAutomation.Core.WebObjects.WebContainer.Attributes;

	[Name("GoogleSearchPage")]
	public partial class GoogleSearchPage 
	{
		[Name("Search")]
		[Xpath("//*[@class='tsf-p']")]
		public IWebComponent Search { get; set; }

		[Name("SearchSearchField")]
		[Xpath("//*[@class='tsf-p']/div[2]//input[1]")]
		public IWebComponent SearchSearchField { get; set; }

		[Name("SearchSearchButton")]
		[Xpath("//*[@class='tsf-p']/div[3]//input[1]")]
		public IWebComponent SearchSearchButton { get; set; }

		[Name("SearchFeelingLuckyButton")]
		[Xpath("//*[@class='tsf-p']/div[3]//input[2]")]
		public IWebComponent SearchFeelingLuckyButton { get; set; }

	}

}

#pragma warning restore
#endregion

